### ISSUE TITLE
Not loading in IE11

### ISSUE THREAD

**Issue by JohnLGI** [ENikS/LINQ#33]
I'm using linq-es2-15 2.4.9 and Angular2 2.0.0. Linq works fine in Chrome and Firefox, but it won't even load in IE11. Any idea what the problem might be?

Thanks,
John

From the IE console:
Error: SyntaxError: Expected identifier
       at ZoneDelegate.prototype.invoke (http://localhost:54040/node_modules/zone.js/dist/zone.js:190:13)
       at Zone.prototype.run (http://localhost:54040/node_modules/zone.js/dist/zone.js:85:17)
       at Anonymous function (http://localhost:54040/node_modules/zone.js/dist/zone.js:451:17)
       at ZoneDelegate.prototype.invokeTask (http://localhost:54040/node_modules/zone.js/dist/zone.js:223:17)
       at Zone.prototype.runTask (http://localhost:54040/node_modules/zone.js/dist/zone.js:125:21)
       at drainMicroTaskQueue (http://localhost:54040/node_modules/zone.js/dist/zone.js:357:25)
    Evaluating http://localhost:54040/node_modules/linq-es2015/dist/linq.js
    Error loading http://localhost:54040/node_modules/linq-es2015/dist/linq.js as "linq-es2015" from http://localhost:54040/app/fc/fc.component.js

**Comment by ENikS** [comment]
IE does not implement EcmaScript-2015 specification and does not provide all the features required by  linq-es2015.
You could use [linq-es5](https://github.com/ENikS/LINQ/tree/linq-es5) in IE with no code changes. These two packages implement exactly the same API but with two different technologies.

You could try adding appropriate shim for the missing features but I personally did not test any of these and can not comment on which one works best.
